### PR TITLE
ENH: Test the similarity metric

### PR DESCRIPTION
**Pull request by jhlegarreta**
Test the similarity metric.

Take advantage of the commit to improve the test style to make a better
use of the ITK macros.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@dzenanz @ntustison I managed to fix the local issues I had yesterday with PR #2 (just had to re-build ITK) and both tests are passing locally. I have not checked what the output images look like. Let's see what the CI builds say. If they pass, this PR would be ready to be merged.

**Review by dzenanz — APPROVED** [review]
We could merge it as-is, but the two denoised outputs are barely different (differences in 5th decimal place). We could keep just one file. If the regression of the other output fails just set a looser tolerance than the default.

**Comment by jhlegarreta** [comment]
> We could merge it as-is, but the two denoised outputs are barely different (differences in 5th decimal place). We could keep just one file. If the regression of the other output fails just set a looser tolerance than the default.

Maybe @ntustison can provide another test image for one of the metrics or another configuration/parameters resulting in two denoised images that are different at the naked eye but still optimal in terms of the metric (?). Otherwise, @dzenanz's proposal seems fair to me.

**Comment by ntustison** [comment]
The additional metric was not tested extensively and ultimately didn't make much difference (as you found), from what I can remember.  But I'd have to go back and look because it was so long ago.

**Comment by ntustison** [comment]
Wait, now I remember---the additional metric was tested in the context of [joint label fusion](https://pubmed.ncbi.nlm.nih.gov/22732662/) which is also derived from the non-local patch-based class.  I don't know that we ever tested the metric in the context of adaptive denoising.

**Comment by jhlegarreta** [comment]
> Wait, now I remember---the additional metric was tested in the context of joint label fusion which is also derived from the non-local patch-based class. I don't know that we ever tested the metric in the context of adaptive denoising.

Then maybe the metric `enum` should be moved to a file on its own, have its class name changed to some other more general name, and have it tested also within a more appropriate or native context?

Personally, I'm fine to have it tested here as well, as it makes sense to me (but maybe I'm wrong). As @dzenanz said, we might be willing to save one file, and add a tolerance parameter for the same output using both metrics. If you feel like it is necessary, less confusing, etc. just let me know, and I'll give it a try.

As for the joint label fusion filter, if I understand correctly, in this [comment](https://github.com/ntustison/ITKAdaptiveDenoising/pull/2#issuecomment-703146129) @ntustison you suggested that the filter is available within `ANTs`. So unless `ANTs` requires the `ITKAdaptiveDenoising` module, it looks difficult to have the metric `enum` somewhere where both tools/modules can use it, unless it is put into `ITK`.

**Comment by dzenanz** [comment]
Once a tagged version is released which contains AdaptiveDenoising module, ANTs can depend on AdaptiveDenoising module.

**Comment by ntustison** [comment]
Yeah, I've already taken out the denoising-specific files from the ANTs repo and it now depends on the module.

**Comment by jhlegarreta** [comment]
> Yeah, I've already taken out the denoising-specific files from the ANTs repo and it now depends on the module.

OK, so then as I see it, everything makes sense as it is now. The tag/hash corresponding to this remote can be updated in ITK, and the package be uploaded to PyPI updading the package version.

**Comment by ntustison** [comment]
Great.  So I have to teach a class but can do that later this afternoon.  Otherwise, someone else can do it.

**Pull request merged**
